
import React from 'react';
import { Message } from '../../types';
import { User, Bot, Loader2, FileText } from 'lucide-react';
import { MarkdownView } from '../UI';

interface ChatMessageProps {
    message: Message;
}

export const ChatMessage: React.FC<ChatMessageProps> = ({ message }) => {
    const isUser = message.role === 'user';
    const isThinking = message.role === 'thinking';

    return (
        <div className={`flex w-full mb-6 ${isUser ? 'justify-end' : 'justify-start'}`}>
            <div className={`flex max-w-[85%] md:max-w-[75%] gap-4 ${isUser ? 'flex-row-reverse' : 'flex-row'}`}>
                {/* Avatar */}
                <div className={`w-8 h-8 rounded-full flex items-center justify-center shrink-0 ${
                    isUser ? 'bg-blue-600' : isThinking ? 'bg-amber-500/10' : 'bg-slate-200 dark:bg-slate-800'
                }`}>
                    {isUser ? <User className="w-5 h-5 text-white" /> : 
                     isThinking ? <Loader2 className="w-5 h-5 text-amber-500 animate-spin" /> :
                     <Bot className="w-5 h-5 text-blue-600 dark:text-blue-400" />}
                </div>

                {/* Content */}
                <div className={`flex flex-col ${isUser ? 'items-end' : 'items-start'}`}>
                    <div className={`px-5 py-3.5 rounded-2xl shadow-sm text-sm leading-relaxed ${
                        isUser 
                          ? 'bg-blue-600 text-white rounded-tr-none' 
                          : isThinking 
                            ? 'bg-white dark:bg-slate-900 border border-amber-500/30 text-slate-600 dark:text-slate-300 rounded-tl-none italic'
                            : 'bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 text-slate-800 dark:text-slate-200 rounded-tl-none'
                    }`}>
                        {isThinking ? (
                            <div className="flex items-center gap-2">
                                <span>{message.content}</span>
                            </div>
                        ) : (
                            <MarkdownView content={message.content} />
                        )}
                    </div>

                    {/* Artifacts Attachment */}
                    {message.artifacts && message.artifacts.length > 0 && (
                        <div className="mt-2 space-y-2 w-full">
                            {message.artifacts.map(art => (
                                <div key={art.id} className="flex items-center gap-3 p-3 bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-xl cursor-pointer hover:border-blue-500 transition-colors group">
                                    <div className="w-10 h-10 bg-blue-50 dark:bg-blue-900/20 rounded-lg flex items-center justify-center">
                                        <FileText className="w-5 h-5 text-blue-600 dark:text-blue-400" />
                                    </div>
                                    <div className="flex-1 min-w-0">
                                        <p className="font-medium text-slate-900 dark:text-slate-100 truncate">{art.filename}</p>
                                        <p className="text-xs text-slate-500 dark:text-slate-400">{art.type.toUpperCase()} • Generated by {art.generatedBy}</p>
                                    </div>
                                </div>
                            ))}
                        </div>
                    )}
                    
                    <span className="text-[10px] text-slate-400 mt-1 px-1">
                        {new Date(message.timestamp).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}
                    </span>
                </div>
            </div>
        </div>
    );
};
